# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.6.2
_src_path: https://github.com/jupyterlab/extension-template
advanced: false
author_email: elisabeth.hannah.juttner@cern.ch
author_name: Elisabeth Jüttner
has_ai_rules: false
has_binder: false
has_settings: false
kind: frontend-and-server
labextension_name: inveniordm_jupyterlab
project_short_description: Integrates InvenioRDM into JupyterLab.
python_name: inveniordm_jupyterlab
repository: https://github.com/vre-hub/inveniordm-jupyterlab-extension
test: true
