{{- if and (not .Values.oauth.existingSecret) .Values.oauth.clientSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inveniordm-api-proxy.secretName" . }}
  labels:
    {{- include "inveniordm-api-proxy.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.oauth.existingSecretKey }}: {{ .Values.oauth.clientSecret | quote }}
{{- end }}
